#### Boston House Price Dataset
- 머신 러닝 등 데이터 분석을 처음 배울 때, 가장 대표적으로 사용하는 Example Dataset
- 1978년에 발표된 데이터로, 미국 인구통계조사 결과 미국 보스턴 지역의 주택 가격에 영향을 준 요소들을 정리함

In [1]:
from sklearn.datasets import load_boston
import matplotlib.pyplot as plt
import numpy as np

In [2]:
boston = load_boston()

In [7]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR'])

In [ ]:
boston["target"]

In [ ]:
print(boston["DESCR"])

In [4]:
x_data = boston.data
y_data = boston.target.reshape(boston.target.size,1)

x_data[:3]

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, 0.0000e+00, 5.3800e-01,
        6.5750e+00, 6.5200e+01, 4.0900e+00, 1.0000e+00, 2.9600e+02,
        1.5300e+01, 3.9690e+02, 4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        6.4210e+00, 7.8900e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9690e+02, 9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        7.1850e+00, 6.1100e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9283e+02, 4.0300e+00]])

In [10]:
from sklearn import preprocessing

minmax_scale = preprocessing.MinMaxScaler().fit(x_data)
x_scaled_data = minmax_scale.transform(x_data)

x_scaled_data[:3]

array([[0.00000000e+00, 1.80000000e-01, 6.78152493e-02, 0.00000000e+00,
        3.14814815e-01, 5.77505269e-01, 6.41606591e-01, 2.69203139e-01,
        0.00000000e+00, 2.08015267e-01, 2.87234043e-01, 1.00000000e+00,
        8.96799117e-02],
       [2.35922539e-04, 0.00000000e+00, 2.42302053e-01, 0.00000000e+00,
        1.72839506e-01, 5.47997701e-01, 7.82698249e-01, 3.48961980e-01,
        4.34782609e-02, 1.04961832e-01, 5.53191489e-01, 1.00000000e+00,
        2.04470199e-01],
       [2.35697744e-04, 0.00000000e+00, 2.42302053e-01, 0.00000000e+00,
        1.72839506e-01, 6.94385898e-01, 5.99382080e-01, 3.48961980e-01,
        4.34782609e-02, 1.04961832e-01, 5.53191489e-01, 9.89737254e-01,
        6.34657837e-02]])

In [11]:
from sklearn import linear_model

regr = linear_model.LinearRegression(fit_intercept=True, 
                                     # 상수항 넣을건지 말건지
                                    normalize=False, 
                                     # 벌써 normalizing해줬으니 안함
                                    copy_X=True, 
                                    # 데이터를 복사해서 사용할지. 일반적으로 True하면 됨
                                    n_jobs=8) #CPU 개수 몇 개 쓸건가 정해줌
regr.fit(x_scaled_data,y_data)
regr
# 모델을 만들어 줌 -> weights의 값이 결정됨

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=8, normalize=False)

In [13]:
regr.coef_, regr.intercept_

(array([[ -9.53495156,   4.63952195,   0.56906733,   2.6885614 ,
          -8.64873871,  19.85700309,   0.07292809, -16.22877191,
           7.03006588,  -6.46057746,  -8.96255741,   3.7248827 ,
         -19.04291078]]), array([26.61291386]))

In [14]:
## The coefficients
print('Coefficients: ', regr.coef_)
print('intercept: ',regr.intercept_)

Coefficients:  [[ -9.53495156   4.63952195   0.56906733   2.6885614   -8.64873871
   19.85700309   0.07292809 -16.22877191   7.03006588  -6.46057746
   -8.96255741   3.7248827  -19.04291078]]
intercept:  [26.61291386]


In [17]:
regr.predict(x_scaled_data[:10])

array([[30.00821269],
       [25.0298606 ],
       [30.5702317 ],
       [28.60814055],
       [27.94288232],
       [25.25940048],
       [23.00433994],
       [19.5347558 ],
       [11.51696539],
       [18.91981483]])

In [15]:
regr.predict(x_data[0].reshape(1,-1))

array([[-483.19114376]])

In [16]:
x_data[0].dot(regr.coef_.T) + regr.intercept_

array([-483.19114376])

### Sampling 적용해보기

In [20]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(x_scaled_data,y_data,test_size=0.2)

In [21]:
len(x_scaled_data)

506

In [22]:
len(X_train)

404

In [23]:
len(X_test)

102

In [26]:
from sklearn import linear_model

regr = linear_model.LinearRegression(fit_intercept=True, 
                                     # 상수항 넣을건지 말건지
                                    normalize=False, 
                                     # 벌써 normalizing해줬으니 안함
                                    copy_X=True, 
                                    # 데이터를 복사해서 사용할지. 일반적으로 True하면 됨
                                    n_jobs=8) #CPU 개수 몇 개 쓸건가 정해줌
regr.fit(X_train,y_train)
regr
# 모델을 만들어 줌 -> weights의 값이 결정됨

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=8, normalize=False)

In [29]:
y_true = y_test
y_pred = regr.predict(X_test)

In [30]:
np.sqrt(((y_true- y_pred) ** 2).sum()/len(y_true))

4.60566369197134

In [33]:
from sklearn.metrics import mean_squared_error
np.sqrt(mean_squared_error(y_true,y_pred))

4.60566369197134